### ISSUE TITLE
Sense Resistor Value

### ISSUE THREAD

**Issue by kAdonis** [hasenbanck/heteromycin#1]
Wow, this project looks awesome!

I am a big fan of the TMC5160 and I am looking forward to see your board running
are you sure about the sense resistor value? I think 0,075 Ohm is a bit low
The advantage is the high motor current of 3,1A, but it could lead to problems for smaller motors

The current is scaled down by Globalscaler and CS, the datasheet recommends CS ≥16 and Globalscaler > 128

![unbenanntzjghv](https://user-images.githubusercontent.com/35379348/47604724-df3bed80-d9fd-11e8-9ae3-f104358da804.JPG)

which means a minimum (recommended) RMS motor current of  820 mA
Most Nema17 motors in 3d Printers need an I rms 600-1000 mA so I would suggest using 
at least 0,1 or 0,12 Ohm sense resistors. 

I see you live in Hamburg, have you talked to Trinamic about your Project?

I am using TMC5160BOB with 0.22 Ohm sense resistors in standalone mode for X and Y in my printer,
running fine (in Stealthchop) at 720mA rms with 1,5A motors

**Comment by hasenbanck** [comment]
Thank you for the feedback! The premise when designing this board was: "Let's make it stupid powerful". In the first iteration I want to test how the board works with totally insane values (3,1 A for 3D printer that use 99% NEMA17 stepper with a max current of 1.2 / 1.5 A ....). That's why I settled with 0.075Ohm sense resistors.

I will test the current setup and want to see how well the stepper driver scale down with GS/CS outside of the recommended values. If those values turn our problematic, I will gladly adjust those values. Luckily the sense resistors are easily adjusted in future versions and can also easily be changed / configured by the end user (if he has a (hot air) solder iron).

Speaking about "stupid powerful": I originally wanted to use the STM32H7 (400 MHz) of the new value line with external flash memory. But sadly their HAL isn't up to standard yet and the Arduino Core doesn't support them yet.

I haven't contacted Trinamic yet. Don't know if this project would be valuable for them or not.

**Comment by hasenbanck** [comment]
The next design (v1.2) will have sense resistor values of 0.1 Ohm. This should act as a more sensible default value and allows for a maximum current of 2.3A.
